### PR TITLE
CMake: Honor OM_QT_MAJOR_VERSION

### PR DESCRIPTION
**Pull request by jschueller**
/cc @adeas31

### CODE REVIEW

**Review by adeas31 — APPROVED** [review]

**Comment by jschueller** [comment]
should we update something in the main repo ?

**Comment by adeas31** [comment]
Yes we need to bump the submodule version.

**Comment by adeas31** [comment]
https://github.com/OpenModelica/OpenModelica/pull/13132

**Comment by jschueller** [comment]
ah thanks

**Comment by jschueller** [comment]
would it be possible to include this into 1.24.3 ?

**Comment by adeas31** [comment]
https://github.com/OpenModelica/OpenModelica/pull/13283

**Comment by jschueller** [comment]
thanks a lot!

**Pull request merged**
